server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: oauth-database
#      username:
#      password:

security:
  oauth2:
    client:
      clientId: ankaboot
      clientSecret: ankaboot
eureka:
  client:
    serviceUrl:
      defaultZone: http://servicediscovery1.com:8761/eureka
  registerWithEureka: true
  fetchRegistry: true